package rabbit

const (
	ENV_RMQ_USERNAME = "RABBIT_USERNAME"
	ENV_RMQ_PASSWORD = "RABBIT_PASSWORD"
	ENV_RMQ_HOST     = "RABBIT_HOST"
	ENV_RMQ_PORT     = "RABBIT_PORT"

	RMQ_QUEUE_NAME_TEXT = "text"
)
